const data = [
        {
            id: 1,
            name: "Nike Shoes",
            description: "Experience unmatched comfort and style with Nike's latest running shoes, featuring lightweight breathability and superior traction for any terrain. Elevate your performance while making a bold statement.",
            categorie:"Men",
            img:"https://i.pinimg.com/236x/b1/76/3b/b1763b273e819ec7cd764b20e179df32.jpg",
            oldPrice: 120,
            newPrice: 95,
        },
        {
            id: 2,
            name: "Adidas Shoes",
            description: "Experience unmatched comfort and style with Adidas's latest running shoes, featuring lightweight breathability and superior traction for any terrain. Elevate your performance while making a bold statement.",
            categorie:"Men",
            img:"https://i.pinimg.com/564x/05/28/b7/0528b7a6e7a44bb27f6abd19559dda3c.jpg",
            oldPrice: 110,
            newPrice: 89,
        },
        {
            id:3,
            name: "Mens Green Long Sleeve",
            description:"Stay effortlessly stylish with this men's green long sleeve shirt, crafted from soft, breathable fabric for all-day comfort. Perfect for layering or wearing on its own, it's a versatile addition to any wardrobe.",
            categorie:"Men",
            img:"https://i.pinimg.com/564x/ed/ba/2c/edba2ca48e35a0aa0c09990841bc66ef.jpg",
            oldPrice:55,
            newPrice:39.99,
        },
        {
            id:4,
            name: "FEATURE Beanies",
            description:"Make our new Watch Cap and Oversized beanies your go-to accessory this season. Introduced with a timeless and quality design, our latest additions are seen in a variety of colorways that can perfectly fit all styles.",
            categorie:"Men",
            img:"https://i.pinimg.com/564x/55/af/24/55af24f1bb7ca33a794e850fafe5c346.jpg",
            oldPrice:25,
            newPrice:19.99,
        },
        {
            id:5,
            name: "Sweatshirt",
            description:"Cozy up in this classic sweatshirt, made from soft, warm fabric for ultimate comfort. Whether you're lounging at home or out and about, its timeless design and relaxed fit make it a go-to essential.",
            categorie:"Men",
            img:"https://i.pinimg.com/564x/9c/39/4d/9c394d7d12b50ed7985d54fcdc1f27d0.jpg",
            oldPrice:35,
            newPrice:29.99,
        },
        {
            id:6,
            name: "Cotton Jacket",
            description:"Layer up with this versatile cotton jacket, offering a perfect blend of style and comfort. With its durable fabric and sleek design, it is an ideal choice for cool, casual outings.",
            categorie:"Men",
            img:"https://i.pinimg.com/564x/32/3b/06/323b06e063524cecc7da5c4421e77197.jpg",
            oldPrice:40,
            newPrice:33,
        },
        {
            id: 7,
            name: "Men's Denim Jacket",
            description: "Classic and rugged, this men's denim jacket adds a cool, timeless edge to any outfit. Perfect for layering over tees or hoodies.",
            categorie: "Men",
            offre:true,
            img: "https://i.pinimg.com/564x/ab/bb/31/abbb31c82f78592829b90e4458368129.jpg",
            oldPrice: 70,
            newPrice: 55,
        },
        {
            id: 8,
            name: "Men's Leather Boots",
            description: "Step out in style with these durable men's leather boots. Crafted for comfort and designed for a sleek, polished look.",
            categorie: "Men",
            offre:true,
            img: "https://i.pinimg.com/564x/d8/e2/e1/d8e2e1f7ef8e63802f737cf8d173241e.jpg",
            oldPrice: 150,
            newPrice: 129.99,
        },
        {
            id: 9,
            name: "Men's Black Polo Shirt",
            description: "A wardrobe staple, this men's black polo shirt offers a blend of comfort and casual style. Ideal for everyday wear.",
            categorie: "Men",
            img: "https://i.pinimg.com/564x/20/e5/5e/20e55e578dde7ceea39c49e06c64327c.jpg",
            oldPrice: 40,
            newPrice: 29.99,
        },
        {
            id: 10,
            name: "Men's Gray Hoodie",
            description: "Stay warm and comfortable in this men's gray hoodie, featuring a soft interior and a relaxed fit. Perfect for casual days.",
            categorie: "Men",
            img: "https://i.pinimg.com/564x/2a/82/28/2a822873888760faf87a8c59a0c82819.jpg",
            oldPrice: 50,
            newPrice: 39.99,
        },
        {
            id: 11,
            name: "Men's Chino Pants",
            description: "Versatile and stylish, these men's chino pants offer a comfortable fit with a modern, tailored silhouette.",
            categorie: "Men",
            img: "https://i.pinimg.com/564x/75/fb/e3/75fbe30a3893cb19139a20533f22d46b.jpg",
            oldPrice: 45,
            newPrice: 34.99,
        },
        {
            id: 12,
            name: "Men's Casual Sneakers",
            description: "These casual sneakers are perfect for everyday wear, providing a blend of style and comfort with their cushioned sole and sleek design.",
            categorie: "Men",
            img: "https://i.pinimg.com/564x/75/ee/8b/75ee8bf2b68d07f6158c9e3f4d5ef3ac.jpg",
            oldPrice: 65,
            newPrice: 49.99,
        },
        {
            id: 13,
            name: "Women's Floral Dress",
            description: "Embrace elegance with this women's floral dress, featuring a flowy silhouette and delicate print that's perfect for any occasion.",
            categorie: "Women",
            img: "https://i.pinimg.com/564x/59/62/2b/59622b0ad244bc5119b121ae10776908.jpg",
            oldPrice: 85,
            newPrice: 69.99,
        },
        {
            id: 14,
            name: "Women's Leather Handbag",
            description: "This women's leather handbag combines style and functionality, offering plenty of space while keeping your look chic and sophisticated.",
            categorie: "Women",
            img: "https://i.pinimg.com/564x/2f/5b/24/2f5b245e341b1d16c529e223d03ec1c0.jpg",
            oldPrice: 120,
            newPrice: 95,
        },
        {
            id: 15,
            name: "Women's High Heels",
            description: "Step into confidence with these women's high heels, designed to elevate your style with their sleek design and comfortable fit.",
            categorie: "Women",
            img: "https://i.pinimg.com/564x/3b/82/f0/3b82f06b9686a16578173fed71cacd70.jpg",
            oldPrice: 100,
            newPrice: 79.99,
        },
        {
            id: 16,
            name: "Women's Trench Coat",
            description: "A timeless piece, this women's trench coat is perfect for layering during transitional weather. Its classic design ensures it never goes out of style.",
            categorie: "Women",
            img: "https://i.pinimg.com/736x/02/1c/07/021c07f5d4090429db8c0ac24f0f4553.jpg",
            oldPrice: 130,
            newPrice: 109.99,
        },
        {
            id: 17,
            name: "Women's Skinny Jeans",
            description: "These women's skinny jeans offer a flattering fit and are made from stretchy fabric for ultimate comfort. A must-have in any wardrobe.",
            categorie: "Women",
            img: "https://i.pinimg.com/564x/a1/b4/e2/a1b4e2ec812247f0babd181dab71974b.jpg",
            oldPrice: 60,
            newPrice: 49.99,
        },
        {
            id: 18,
            name: "Women's Running Shoes",
            description: "Stay active in style with these women's running shoes, featuring a lightweight design and superior support for your daily workouts.",
            categorie: "Women",
            img: "https://i.pinimg.com/564x/df/fb/e3/dffbe3aa50705c053df18d74a8343e31.jpg",
            oldPrice: 90,
            newPrice: 74.99,
        },
        {
            id: 19,
            name: "Kid's Striped T-Shirt",
            description: "This kid's striped t-shirt is both playful and comfortable, perfect for everyday wear. Made from soft cotton for all-day comfort.",
            categorie: "Kids",
            img: "https://i.pinimg.com/564x/47/a9/56/47a9560484c1fa99008c7678f282119d.jpg",
            oldPrice: 25,
            newPrice: 19.99,
        },
        {
            id: 20,
            name: "Kid's Denim Overalls",
            description: "These kid's denim overalls are durable and stylish, perfect for active play. Pair with a t-shirt for a classic, casual look.",
            categorie: "Kids",
            popular:true,
            img: "https://i.pinimg.com/564x/9a/68/92/9a68926823b0e1f1c5b0b7e9a660bbc1.jpg",
            oldPrice: 50,
            newPrice: 39.99,
        },
        {
            id: 21,
            name: "Kid's Winter Coat",
            description: "Keep your little one warm and cozy with this kid's winter coat, featuring a padded interior and a stylish design.",
            categorie: "Kids",
            popular:true,
            img: "https://i.pinimg.com/564x/96/72/b8/9672b885c4b7fc2df88b60ef98ebab9c.jpg",
            oldPrice: 70,
            newPrice: 55,
        },
        {
            id: 22,
            name: "Kid's Sneakers",
            description: "These kid's sneakers are perfect for playtime, offering comfort and durability with a fun, colorful design.",
            categorie: "Kids",
            img: "https://i.pinimg.com/736x/6c/1c/7b/6c1c7b574bd0362d1a58af8ffad53c12.jpg",
            oldPrice: 45,
            newPrice: 34.99,
        },
        {
            id: 23,
            name: "Kid's Hoodie",
            description: "Soft and cozy, this kid's hoodie is perfect for cooler days. It features a fun design that kids will love.",
            categorie: "Kids",
            img: "https://i.pinimg.com/564x/25/2c/87/252c87093da0e69d22aa883b951c6b77.jpg",
            oldPrice: 35,
            newPrice: 29.99,
        },
        {
            id: 24,
            name: "Kid's Pajama Set",
            description: "This kid's pajama set is made from soft, breathable fabric, ensuring a comfortable night's sleep with a fun, playful design.",
            categorie: "Kids",
            img: "https://i.pinimg.com/564x/41/d4/cf/41d4cf3a9cf9fbb45a4fbeedda30804e.jpg",
            oldPrice: 30,
            newPrice: 24.99,
        },
        {
            id: 25,
            name: "Men's Wool Scarf",
            description: "Stay warm and stylish with this men's wool scarf. Its soft texture and versatile design make it a must-have for cold weather.",
            categorie: "Men",
            img: "https://i.pinimg.com/564x/53/04/92/530492f025b7404b99fec87d11fc3db8.jpg",
            oldPrice: 40,
            newPrice: 29.99,
        },
        {
            id: 26,
            name: "Women's Ankle Boots",
            description: "Step out in confidence with these women's ankle boots, featuring a sleek design and comfortable fit, perfect for any occasion.",
            categorie: "Women",
            img: "https://i.pinimg.com/564x/fc/4a/4f/fc4a4fe111dfb0734fabbcaa048d0426.jpg",
            oldPrice: 100,
            newPrice: 79.99,
        },
        {
            id: 27,
            name: "Kid's Rain Boots",
            description: "Keep your child's feet dry and stylish with these kid's rain boots, featuring a fun design and waterproof construction.",
            categorie: "Kids",
            img: "https://i.pinimg.com/736x/df/cb/12/dfcb12e3eb90f11aadf8faf3e51fa89c.jpg",
            oldPrice: 40,
            newPrice: 29.99,
        },
        {
            id: 28,
            name: "Women's Leather Belt",
            description: "Complete your outfit with this women's leather belt, offering a sleek design and durable construction for everyday wear.",
            categorie: "Women",
            img: "https://i.pinimg.com/564x/96/22/36/962236a70406dc9bf6c2e9f642fba95d.jpg",
            oldPrice: 50,
            newPrice: 39.99,
        },
        {
            id: 29,
            name: "Men's Beanie",
            description: "Keep warm with this men's beanie, designed with a snug fit and soft fabric for maximum comfort during cold days.",
            categorie: "Men",
            img: "https://i.pinimg.com/564x/b0/24/f2/b024f278520e56554c20dd5b9e9abee4.jpg",
            oldPrice: 25,
            newPrice: 19.99,
        },
        {
            id: 30,
            name: "Women's Workout Leggings",
            description: "Move with ease in these women's workout leggings, offering a snug fit and breathable fabric for maximum comfort during exercise.",
            categorie: "Women",
            img: "https://i.pinimg.com/564x/be/6b/4f/be6b4f8680b6106e0026508a04dc3de2.jpg",
            oldPrice: 45,
            newPrice: 34.99,
        },
        {
            id: 31,
            name: "Kid's Graphic Tee",
            description: "This kid's graphic tee is perfect for playful days, featuring a fun design and soft cotton fabric for all-day comfort.",
            categorie: "Kids",
            popular:true,
            img: "https://i.pinimg.com/564x/bd/f0/70/bdf0701d3102cb064299b6bb04325f12.jpg",
            oldPrice: 20,
            newPrice: 14.99,
        },
        {
            id: 32,
            name: "Women's Maxi Skirt",
            description: "This women's maxi skirt is a versatile addition to your wardrobe, offering a flowy silhouette and a comfortable fit.",
            categorie: "Women",
            img: "https://i.pinimg.com/564x/19/49/00/194900d5f7b4aabe6f3ecf5da52a5462.jpg",
            oldPrice: 60,
            newPrice: 49.99,
        },
        {
            id: 33,
            name: "Men's Casual Blazer",
            description: "Add a touch of sophistication with this men's casual blazer, perfect for smart-casual occasions with its tailored fit and classic design.",
            categorie: "Men",
            img: "https://i.pinimg.com/564x/92/fb/b4/92fbb4d6567d6b2ce1de932eb765a031.jpg",
            oldPrice: 120,
            newPrice: 99.99,
        },
        {
            id: 34,
            name: "Kid's Sun Hat",
            description: "Protect your child from the sun with this kid's sun hat, featuring a wide brim and a fun, colorful design.",
            categorie: "Kids",
            img: "https://i.pinimg.com/564x/2a/24/8f/2a248f1e39e31f0d9f18a0397759afc9.jpg",
            oldPrice: 20,
            newPrice: 14.99,
        },
        {
            id: 35,
            name: "Women's Peacoat",
            description: "Stay warm and stylish in this women's peacoat, featuring a classic double-breasted design and a flattering fit.",
            categorie: "Women",
            img: "https://i.pinimg.com/736x/bd/e6/fc/bde6fc44060c576dbea8ee51559304d6.jpg",
            oldPrice: 130,
            newPrice: 109.99,
        },
        {
            id: 36,
            name: "Men's Flannel Shirt",
            description: "Stay cozy in this men's flannel shirt, offering a comfortable fit and a classic plaid design that's perfect for layering.",
            categorie: "Men",
            img: "https://i.pinimg.com/564x/84/f1/cd/84f1cd725d84bc83b437fc3bfbe7590c.jpg",
            oldPrice: 45,
            newPrice: 34.99,
        },
]; 

export default data;